export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_INSTANCE = 'SET_INSTANCE';
export const SET_ISLOADING = 'SET_ISLOADING';
export const UPDATE_INSTANCE = 'UPDATE_INSTANCE';
export const UPDATE_ONBOARDING_PROGRESS = 'UPDATE_ONBOARDING_PROGRESS';
