import auth0 from 'auth0-js';
import config from './conf';

class Auth {
  constructor(config) {
    //this.baseUrl = config.baseUrl;
    this.clientID = config.clientID;
    this.auth0 = new auth0.WebAuth({
      domain: config.domain,
      audience: config.audience,
      clientID: config.clientID,
      redirectUri: config.callbackUrl,
      responseType: config.responseType,
      scope: config.scope,
    });
    this.checkingSession = false;

    this.scheduleTokenRenewal();
  }

  // Returns the access token for use in authenticated XHR requests.
  getAccessToken = () => {
    return this.accessToken;
  }

  // Returns the idToken generated by Auth0 for the current user.
  getIdToken = () => {
    return this.idToken;
  }

  // Returns the profile of the authenticated user, if any.
  getProfile = () => {
    return this.profile;
  }

  // => Boolean
  getCheckingSession = () => {
    return this.checkingSession.toString();
  }

  // Called after the user is redirected from Auth0.  This method reads the hash segment
  // of the URL to fetch the user details and the id token.
  handleAuthentication = () => {
    return new Promise((resolve, reject) => {
      this.auth0.parseHash((err, authResult) => {
        if (err) return reject(err);
        if (!authResult || !authResult.idToken) return reject(err);
        /*this.setSession(authResult);
        resolve();*/
        resolve(authResult);
      });
    })
    .then(authResult => this.setSession(authResult));
  }

  // => Boolean
  isAuthenticated = () => {
    return new Date().getTime() < this.expiresAt;
  }

  // set auth creds on the instance
  setSession = (authResult, step) => {
    this.accessToken = authResult.accessToken;
    this.idToken = authResult.idToken;
    this.profile = authResult.idTokenPayload;
    this.checkingSession = false;
    // set the time that the id token will expire at
    this.expiresAt = authResult.expiresIn * 1000 + new Date().getTime();
    console.log(this);
    this.scheduleTokenRenewal();
  }
  /*setSession(authResult) {
    this.idToken = authResult.idToken;
    this.profile = authResult.idTokenPayload;
    // set the time that the id token will expire at
    this.expiresAt = authResult.idTokenPayload.exp * 1000;
  }*/

  tokenRenewalTimeout;

  // Redirects to Auth0 login page
  signIn = () => {
    this.auth0.authorize();
  }

  // sets profile, id_token, expiresAt to null
  signOut = () => {
    clearTimeout(this.tokenRenewalTimeout);
    this.auth0.logout({
      returnTo: window.location.origin,
      clientID: this.clientID,
    });
  }
  /*signOut() {
    this.auth0.logout({
      returnTo: this.baseUrl,
      //returnTo: window.location.origin,
      clientID: this.clientID,
    });
  }*/

  checkSession = () => {
    this.checkingSession = true;
    return new Promise((resolve, reject) => {
      this.auth0.checkSession({}, (err, authResult) => {
        this.checkingSession = false;
        if (err) return reject(err);
        resolve(authResult);
        /*this.setSession(authResult);
        resolve();*/
      });
    });
  }

  // check session and sets the auth tokens in memory on the Auth instance
  renewTokens = async () => {
    return this.checkSession()
    .then(authResult => this.setSession(authResult))
  }

  scheduleTokenRenewal = () => {
    const delay = this.expiresAt - Date.now();
    console.log(delay);
    if (delay > 0) {
      this.tokenRenewalTimeout = setTimeout(() => {
        this.renewTokens();
      }, delay);
    }
  }
}

//const auth0Client = new Auth();
const auth0Client = new Auth(config.AUTH0);

export default auth0Client;