import {
    Add as AddIcon,
    ShowChart as AnalyticsIcon,
    AssignmentInd as BoardIcon,
    FormatPaint as BrandingIcon,
    Dashboard as DashboardIcon,
    Done as DoneIcon,
    Edit as EditIcon,
    Email as EmailIcon,
    ExpandLess as ExpandLessIcon,
    ExpandMore as ExpandMoreIcon,
    SaveAlt as ExportIcon,
    OpenInNew as ExternalLinkIcon,
    Build as GetStartedIcon,
    Help as HelpIcon,
    Group as MembershipIcon,
    Menu as MenuIcon,
    NewReleases as NewIcon,
    Business as OrganizationInfoIcon,
    AttachMoney as PaymentsIcon,
    TrackChanges as SocialMediaIcon,
    ViewList as ViewListIcon,
    Web as WebsiteIcon
} from '@material-ui/icons';
import {
    CalendarPlus as AddEventIcon,
    FilePlus as AddPostIcon,
    MessagePlus as AddSocialMediaIcon,
    AccountTie as AlumniIcon,
    ArrowDown as ArrowDownIcon,
    ArrowRight as ArrowRightIcon,
    Palette as BrandingColorsIcon,
    ImageMultiple as BrandingImagesIcon,
    Bank as BylawsIcon,
    ClipboardFlow as ChangeBoardIcon,
    LockReset as ChangePasswordIcon,
    Gift as DonationsIcon,
    AccountHeart as DonorIcon,
    CalendarEdit as EditEventsIcon,
    FileDocumentEdit as EditPostsIcon,
    Calendar as EventIcon,
    Facebook as FacebookIcon,
    LockQuestion as ForgotPasswordIcon,
    GoogleAnalytics as GoogleAnalyticsIcon,
    Google as GoogleIcon,
    AlertOctagon as IveBeenHackedIcon,
    Rocket as LaunchIcon,
    Mailbox as MailingAddressIcon,
    Account as MemberIcon,
    FacebookMessenger as MessengerIcon,
    MessageProcessing as OtherSocialMediaIcon,
    Paypal as PayPalIcon,
    Dialpad as PhoneNumberIcon,
    Podcast as PodcastIcon,
    FileDocument as PostsIcon,
    ContentSave as SaveIcon,
    Headset as StartPodcastIcon,
    AccountConvert as SustainerIcon,
    FormatQuoteClose as TaglineDescriptionIcon,
    Twitter as TwitterIcon,
    BankTransfer as UpdateBylawsIcon,
    Wordpress as WordPressIcon
} from 'mdi-material-ui';

export {
    AddEventIcon,
    AddIcon,
    AddPostIcon,
    AddSocialMediaIcon,
    AlumniIcon,
    AnalyticsIcon,
    ArrowDownIcon,
    ArrowRightIcon,
    BoardIcon,
    BrandingColorsIcon,
    BrandingIcon,
    BrandingImagesIcon,
    BylawsIcon,
    ChangeBoardIcon,
    ChangePasswordIcon,
    DashboardIcon,
    DonationsIcon,
    DoneIcon,
    DonorIcon,
    EditEventsIcon,
    EditIcon,
    EditPostsIcon,
    EmailIcon,
    EventIcon,
    ExpandLessIcon,
    ExpandMoreIcon,
    ExportIcon,
    ExternalLinkIcon,
    FacebookIcon,
    ForgotPasswordIcon,
    GetStartedIcon,
    GoogleAnalyticsIcon,
    GoogleIcon,
    HelpIcon,
    IveBeenHackedIcon,
    LaunchIcon,
    MailingAddressIcon,
    MemberIcon,
    MembershipIcon,
    MenuIcon,
    MessengerIcon,
    NewIcon,
    OrganizationInfoIcon,
    OtherSocialMediaIcon,
    PaymentsIcon,
    PayPalIcon,
    PhoneNumberIcon,
    PodcastIcon,
    PostsIcon,
    SaveIcon,
    SocialMediaIcon,
    StartPodcastIcon,
    SustainerIcon,
    TaglineDescriptionIcon,
    TwitterIcon,
    UpdateBylawsIcon,
    ViewListIcon,
    WebsiteIcon,
    WordPressIcon
};